//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int ID { get; set; }
        public int LeadID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CallDateTime { get; set; }
        public int Duration { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual User User { get; set; }
    }
}
